### ISSUE TITLE
Build error:  Assertion `args[1]->IsString()' failed.

### ISSUE THREAD

**Issue by dsamoylov** [modularcode/modular-admin-html#109]
When I run `npm start` on Windows, I got following output

```
gulp[12384]: src\node_contextify.cc:631: Assertion `args[1]->IsString()' failed.
 1: 00007FF67F7D82F5
 2: 00007FF67F7B4156
 3: 00007FF67F7B4221
 4: 00007FF67F78A69A
 5: 00007FF67FDD5EB2
 6: 00007FF67FDD7008
 7: 00007FF67FDD636D
 8: 00007FF67FDD628B
 9: 000000A71C0841C1
```

Full node log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\dsamo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle modular-admin-html@1.3.0~prestart: modular-admin-html@1.3.0
6 info lifecycle modular-admin-html@1.3.0~start: modular-admin-html@1.3.0
7 verbose lifecycle modular-admin-html@1.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle modular-admin-html@1.3.0~start: PATH: C:\Users\dsamo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Clouds\Git\modular-admin-html\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\dsamo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\dsamo\AppData\Roaming\npm
9 verbose lifecycle modular-admin-html@1.3.0~start: CWD: C:\Clouds\Git\modular-admin-html
10 silly lifecycle modular-admin-html@1.3.0~start: Args: [ '/d /s /c', 'npm run gulp' ]
11 silly lifecycle modular-admin-html@1.3.0~start: Returned: code: 134  signal: null
12 info lifecycle modular-admin-html@1.3.0~start: Failed to exec start script
13 verbose stack Error: modular-admin-html@1.3.0 start: `npm run gulp`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\dsamo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\dsamo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid modular-admin-html@1.3.0
15 verbose cwd C:\Clouds\Git\modular-admin-html
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dsamo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.6.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 134
22 error modular-admin-html@1.3.0 start: `npm run gulp`
22 error Exit status 134
23 error Failed at the modular-admin-html@1.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

```

**Comment by steelywing** [comment]
This is related to [`gulp` issue](https://github.com/gulpjs/gulp/issues/2162), delete the `package-lock.json` and `node_modules/`, run `npm install` again should work.

**Comment by PrOpOvEdNiK** [comment]
Just do `$ npm i natives`

**Comment by imran-uk** [comment]
> This is related to [gulp issue](https://github.com/gulpjs/gulp/issues/2162), delete the `package-lock.json` and `node_modules/`, run `npm install` again should work.

This solved it for me, thank you.
