### ISSUE TITLE
Cant NPM Start, gulp error

### ISSUE THREAD

**Issue by Sirullrick** [modularcode/modular-admin-html#70]
When I write on my CMD npm start it gets me this error:

> >0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\Jesus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'gulp' ]
> 2 info using npm@5.3.0
> 3 info using node@v6.11.2
> 4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
> 5 info lifecycle modular-admin-html@1.2.0~pregulp: modular-admin-html@1.2.0
> 6 info lifecycle modular-admin-html@1.2.0~gulp: modular-admin-html@1.2.0
> 7 verbose lifecycle modular-admin-html@1.2.0~gulp: unsafe-perm in lifecycle true
> 8 verbose lifecycle modular-admin-html@1.2.0~gulp: PATH: C:\Users\Jesus\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files (x86)\Ampps\www\misahualli\admin\modular-admin-html-master\node_modules\.bin;C:\Users\Jesus\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Program Files (x86)\Ampps\www\misahualli\admin\modular-admin-html-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Ruby24-x64\bin;C:\Users\Jesus\AppData\Roaming\npm
> 9 verbose lifecycle modular-admin-html@1.2.0~gulp: CWD: C:\Program Files (x86)\Ampps\www\misahualli\admin\modular-admin-html-master
> 10 silly lifecycle modular-admin-html@1.2.0~gulp: Args: [ '/d /s /c', 'gulp --gulpfile build/gulpfile.js' ]
> 11 silly lifecycle modular-admin-html@1.2.0~gulp: Returned: code: 1  signal: null
> 12 info lifecycle modular-admin-html@1.2.0~gulp: Failed to exec gulp script
> 13 verbose stack Error: modular-admin-html@1.2.0 gulp: `gulp --gulpfile build/gulpfile.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Jesus\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
> 13 verbose stack     at emitTwo (events.js:106:13)
> 13 verbose stack     at EventEmitter.emit (events.js:191:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Jesus\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 13 verbose stack     at emitTwo (events.js:106:13)
> 13 verbose stack     at ChildProcess.emit (events.js:191:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:891:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 14 verbose pkgid modular-admin-html@1.2.0
> 15 verbose cwd C:\Program Files (x86)\Ampps\www\misahualli\admin\modular-admin-html-master
> 16 verbose Windows_NT 6.1.7601
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jesus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
> 18 verbose node v6.11.2
> 19 verbose npm  v5.3.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error modular-admin-html@1.2.0 gulp: `gulp --gulpfile build/gulpfile.js`
> 22 error Exit status 1
> 23 error Failed at the modular-admin-html@1.2.0 gulp script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

Npm install and bower install with no errors. What Should I do to fix this and run the theme? Thanks.

**Comment by modularcoder** [comment]
Hi @Sirullrick 
Thanks for the report

I'll check on my Windows

**Comment by Omnia-Code** [comment]
I can confirm that it doesn't work on windows.

**Comment by modularcoder** [comment]
@Sirullrick  @Omnia-Code 
This is kinda strange. I was able to run the project on Windows with same configuration.


```
E:\Node\_playground\modular-admin-html>node -v
v6.11.2

E:\Node\_playground\modular-admin-html>npm -v
5.3.0
```

```
E:\Node\_playground\modular-admin-html>npm start

> modular-admin-html@1.2.0 start E:\Node\_playground\modular-admin-html
> npm run gulp


> modular-admin-html@1.2.0 gulp E:\Node\_playground\modular-admin-html
> gulp --gulpfile build/gulpfile.js

[06:47:46] Working directory changed to E:\Node\_playground\modular-admin-html\build
[06:47:46] Using gulpfile E:\Node\_playground\modular-admin-html\build\gulpfile.js
[06:47:46] Starting 'app-assets'...
[06:47:46] Finished 'app-assets' after 104 ms
[06:47:46] Starting 'app-pages'...
[06:47:46] Finished 'app-pages' after 73 ms
[06:47:46] Starting 'app-scripts'...
[06:47:46] Finished 'app-scripts' after 15 ms
[06:47:46] Starting 'app-styles'...
[06:47:47] Finished 'app-styles' after 396 ms
[06:47:47] Starting 'app-themes'...
[06:47:47] Finished 'app-themes' after 37 ms
[06:47:47] Starting 'vendor-assets'...
[06:47:47] Finished 'vendor-assets' after 2.69 ms
[06:47:47] Starting 'vendor-scripts'...
[06:47:47] Finished 'vendor-scripts' after 10 ms
[06:47:47] Starting 'vendor-styles'...
[06:47:47] Finished 'vendor-styles' after 3.39 ms
[06:47:47] Starting 'build'...
[06:47:47] Finished 'build' after 1.71 μs
[06:47:47] Starting 'watch'...
[06:47:47] Finished 'watch' after 43 ms
[06:47:47] Starting 'connect'...
[06:47:47] Finished 'connect' after 11 ms
[06:47:47] Starting 'develop'...
[06:47:47] Finished 'develop' after 1.99 μs
[06:47:47] Starting 'default'...
[06:47:47] Finished 'default' after 1.42 μs
[06:47:47] Server started http://localhost:4000
[06:47:47] LiveReload started on port 35729
```

Maybe this is something to do with your node permissions or other apps running on the port 4000?

**Comment by Omnia-Code** [comment]
Oh, I didn't see that @Sirullrick is talking about the v1 (master). I was trying to build v2.
Are they different to build @modularcoder?

**Comment by coscho** [comment]
I had the same problem. In my case port 4000 war busy. the problem was fixed killing all processes on port 4000.
